config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  devise_for :users
  
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    get "search_form" => "users#search_form"
    resource :relationships,only: [:create,:destroy]
    # get :followings, on: :member
    # get :followers, on: :member
    #あるユーザーがフォローする人全員を表示するルーティング
    #あるユーザーをフォローしてくれている人全員を表示するルーティング(つまりフォロワー)
    #on: :menberと書く事で、ルーティングにidを持たせることができる
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  
  resources :groups do
    get "join" => "groups#join"
    post "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users,through: :group_users
  
  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :group_image
  
  def get_group_image
    (group_image.attached?) ? group_image : 'no_image.jpg'
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]
  
  def index
    @book = Book.new
    @groups = Group.all
  end

  def show
    @book = Book.new
    @user =User.find(user_id)
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit
  end
  
  def join
    @group = Group.find(params[:group_id])
    @group.users << current_user #@group.usersに、current_userを追加しているということ
    redirect_to  groups_path
  end
  
  def new_mail
    @group = Group.find(params[:group_id])
  end

  def send_mail
    @group = Group.find(params[:group_id])
    group_users = @group.users
    @mail_title = params[:mail_title]
    @mail_content = params[:mail_content]
    ContactMailer.send_mail(@mail_title, @mail_content,group_users).deliver
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render "edit"
    end
  end
  
  def destroy
    @group = Group.find(params[:id])
    @group.users.destroy(current_user)#current_userは、@group.usersから消されるという記述。
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :group_image)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th></th>
      <th>グループ名</th>
      <th>紹介文</th>
      <th>メンバー数</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
      <tr>
        <td><%= image_tag group.get_group_image, size:'70x70' %></td>
        <td><%= link_to group.name , group_path(group) %></td>
        <td><%= group.introduction %></td>
        <td><%= group.group_users.count %></td>
        <td>
        <% if group.owner_id == current_user.id %>
        <%= link_to 'Edit', edit_group_path(group), class: "btn btn-sm btn-success " %>
        <!--edit_book_#{@book.id}-->
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/_show.html.erb
<table class='table'>
  <th></th>
  <th>グループ名</th>
  <th>紹介文</th>
  <th>メンバー</th>
  <th colspan = "3"></th>
    <tr>
      <td><%= image_tag group.get_group_image, size:'50x50' %></td>
      <td><%= group.name %></td>
      <td><%= group.introduction %></td>
      <td>
        <% group.users.each do |member| %>
        <p><%= member.name %></p>
        <% end %>
      </td>
      <td nowrap>
       <% if group.owner_id != current_user.id %>
        <% if group.users.include?(current_user) %>
         <%= link_to group_path(group), method: :delete do %>
         <button class = "btn btn-danger">Leave this group</button>
         <% end %>
        <% else %>
         <%= link_to group_join_path(group), method: :post do %>
         <button class = "btn btn-success">Join this group</button>
         <% end %>
        <% end %>
       <% end %>
      </td>
      <% if group.owner_id == current_user.id %>
       <td><%= link_to 'Edit', edit_group_path(group), class: "btn btn-sm btn-success " %></td>
       <td><%= link_to 'Notice an Event', group_new_mail_path(group), class: "btn btn-sm btn-primary " %></td>  
      <% end %>
      
    </tr>
</table>

app/views/groups/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Editing Group</h2>
    <%= form_with model:@group, local:true do |f| %>
      <%= render 'layouts/errors', obj: @group %>
      <div class="form-group">
        <%= f.label :グループ名 %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
      <div class="form-group">
        <%= f.label :紹介文 %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.label :グループ画像 %>
        <%= f.file_field :group_image, class: "form-control-file group_image", accept: 'image/*' %>
      </div>
     
      <div class="form-group">
        <%= f.submit "Create Group" ,class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Groups</h2>
      <%= render 'index',groups: @groups %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Create Group</h2>
    <%= form_with model:@group, local:true do |f| %>
      <%= render 'layouts/errors', obj: @group %>
      <div class="form-group">
        <%= f.label :グループ名 %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
      <div class="form-group">
        <%= f.label :紹介文 %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.label :グループ画像 %>
        <%= f.file_field :group_image, class: "form-control-file group_image", accept: 'image/*' %>
      </div>
     
      <div class="form-group">
        <%= f.submit "Create Group" ,class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Event Mail</h2>
      <!--<h2><%#=@group.name %>メンバーへのメール</h2>-->
    <%= form_with url: group_send_mail_path(@group),method: :get, local: true do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :mail_title,class:'form-control'%>
      </div>
      <div class="form-group">
        <%=f.label:content %>
        <%= f.text_area :mail_content,class:'form-control' %>
      </div>
      <div class="form-group text-right">
       <%= f.submit "送信" ,class: 'btn btn-success' %>
      </div>
    <% end %>
   </div>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3 class="margin_top">送信が完了しました</h3><br>
      <div class="main_width">
        <div class="margin_top">内容は以下の通りです。</div><br>
        <div class="small_margin_top">
          [タイトル]<p class="font-weight-bold"> <%= @mail_title %></p>
        </div>
        <div>
          [本文]<p class="font-weight-bold"> <%= safe_join(@mail_content.split("\n"),tag(:br)) %></p>
        </div><br>
      </div>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %><br>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Group Detail</h2>
      <%= render 'show',group: @group %>
    </div>
  </div>
</div>