config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  devise_for :users
  
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    get "search_form" => "users#search_form"
    resource :relationships,only: [:create,:destroy]
    # get :followings, on: :member
    # get :followers, on: :member
    #あるユーザーがフォローする人全員を表示するルーティング
    #あるユーザーをフォローしてくれている人全員を表示するルーティング(つまりフォロワー)
    #on: :menberと書く事で、ルーティングにidを持たせることができる
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  
  resources :groups do
    get "join" => "groups#join"
    post "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         

  has_many :books
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # has_many :messages, dependent: :destroy
  # has_many :entries, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :group_users
  has_many :groups,through: :group_users
  
  #1 フォローされる側なのか、フォローする側かのhas_manyかわからないので、foreign_keyを設定してフォローする側からのhas_manyだと認識させてあげる
  has_many :relationships, class_name: "Relationship",foreign_key: :following_id, dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  #1とは逆にフォローされる側からのhas_manyだと認識させてあげるが、relationshipsと記述すると、フォローする側のアソシエーションと重複してしまうので、reverse_of_を使用する
  #但し、reverse_of_relationshipsのテーブルを見つけようとするので、class_nameを使ってrelationshipテーブルであると認識させる。
  
  #フォローしている人全員の情報を取得するので、任意名ですが、followingsと記述
  #has_many_throughにて中間テーブルを経由して情報を持ってくる際に使用する。その為、今回はrelationshipsと記述
  #relationshipsから何の情報をとってくるのか、これを指定する際にsourceを使用する
  #あるアカウントがフォローしている情報をリレーションシップの中間テーブルを経由してフォローされる側の情報を抽出するという記述の意味となる。
  has_many :followings, through: :relationships, source: :follower
  has_many :followers, through: :reverse_of_relationships, source: :following
  #あるユーザーをフォローしてくれている人を抽出する
  #自分をフォローしてくれる人の情報を全部取ってくる記述なので、source: :followingとなる
  
  #あるユーザが引数で渡されたUserにフォローされているのか否か判定できるメソッド
  def followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end
  
  # # フォローしたときの処理
  # def follow(user_id)
  # relationships.create(follower_id: user_id)
  # end
  # # フォローを外すときの処理
  # def unfollow(user_id)
  # relationships.find_by(follower_id: user_id).destroy
  # end
  # # フォローしているか判定
  # def following?(user)
  # followings.include?(user)
  # end
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  
  
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    
    #@books = @user.books.page(params[:page]).reverse_order
    @today_book =  @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end
  
  def search_form
    
    @user = User.find(params[:user_id])
    @books = @user.books.where(created_at: params[:created_at].to_date.all_day)
    render :search_form
    # if params[:created_at] == ""
    #   @search_book = "日付を選択してください"
    # else
    #   create_at = params[:created_at]
    #   @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
    # end
  end



  def index
    @users = User.all
    @book = Book.new
    #@users = User.where.not(id:cuurent_user.id)
  end
  
  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_daily_posts_form.html.erb
<br>
<div class='col-md-5'>
  <%= form_with url: user_daily_posts_path(user), method: :get, class: "row justify-content-center", local: false do |f| %>
    <div class="col-auto">
      <%= f.date_field :created_at, class: "form-control" %>
    </div>
    <div class="col-auto">
      <%= f.submit "検索" , class: "btn btn-primary"%>
    </div>
  <% end %>
</div>
<br>
<div class="daily_posts_table">
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="5"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count%></td>
        <td>フォロワー数：<%= user.followers.count%></td>
        <td>
          <% unless user == current_user %>
           <% if user.followed_by?(current_user) %>
            <%= link_to user_relationships_path(user.id), method: :delete do %>
            <p>フォロー外す</p>
            <% end %>
           <% else %>
            <%= link_to user_relationships_path(user.id), method: :post do %>
            <p>フォローする</p>
            <% end %>
           <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
	  <th>follows</th>
	  <th><%= link_to user.followings.count, user_followings_path(user) %></th>
	</tr>
	<tr>
	  <th>followers</th>
	  <th><%= link_to user.followers.count, user_followers_path(user) %></th>
	</tr>
  <tr>
    <!--フォロー・フォロワー機能-->
    <th colspan = "3">
        <% unless user == current_user %>
        <%# if current_user.following?(user) %>
        <% if user.followed_by?(current_user) %>
        <%= link_to user_relationships_path(user.id), method: :delete do %>
        <button class = "btn btn-sm btn-danger">フォロー外す</button>
        <% end %>
        <% else %>
        <%= link_to user_relationships_path(user.id), method: :post do %>
        <button class = "btn btn-sm btn-success">フォローする</button>
        <% end %>
        <% end %>
        <% end %>
        &nbsp;
        <!--チャット機能-->
        <% unless user.id == current_user.id %>
        <% if (current_user.followed_by? @user) && (@user.followed_by? current_user)  %>
        <%= link_to 'チャット始める', chat_path(@user.id), class: "btn btn-sm btn-primary" %>
        <% end %>
        <% end %>
    </th>
  </tr>
</table>
<!--ユーザー編集-->
<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/_record.html.erb
<h2>投稿数の前日比・前週比</h2>
 <table class='table table-bordered'>
   <th>今日の投稿数</th>
   <th>前日の投稿数</th>
   <th>前日比</th>
    <tr>
      <td><%= @today_book.count %></td>
      <td><%= @yesterday_book.count %></td>
      <% if @yesterday_book.count == 0 %>
        <td>  0% </td>
      <% else %>
        <td><% @the_day_before = @today_book.count / @yesterday_book.count.to_f  %>
            <%= (@the_day_before * 100).round %>%</td>
      <% end %>
    </tr>
    </table>
  </table>
  
  <table class='table table-bordered'>
   <th>今週の投稿数</th>
   <th>前週の投稿数</th>
   <th>前週比</th>
    <tr>
      <td><%= @this_week_book.count %></td>
      <td><%= @last_week_book.count %></td>
     <% if @last_week_book.count == 0 %>
      <td> 0 % </td>
     <% else %>
       <td><% @the_week_before = @this_week_book.count / @last_week_book.count.to_f %>
           <%= (@the_week_before * 100).round %>%</td>
     <% end %>
    </tr>
  </table>
  
  <table class='table table-bordered'>
    <th>6日前</th>
    <th>5日前</th>
    <th>4日前</th>
    <th>3日前</th>
    <th>2日前</th>
    <th>1日前</th>
    <th>今日</th>
     <tr>
       <th><%= @books.created_6days.count %></th>
       <th><%= @books.created_5days.count %></th>
       <th><%= @books.created_4days.count %></th>
       <th><%= @books.created_3days.count %></th>
       <th><%= @books.created_2days.count %></th>
       <th><%= @yesterday_book.count %></th>
       <th><%= @today_book.count %></th>
     </tr>
  </table>

   <canvas id="myLineChart"></canvas>
  <script>
    $(document).on('turbolinks:load', function() {
      var ctx = document.getElementById("myLineChart");
      var myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
          datasets: [
            {
              label: '投稿した本の数',
              data: [
                <%= @books.created_6days.count %>,
                <%= @books.created_5days.count %>, 
                <%= @books.created_4days.count %>, 
                <%= @books.created_3days.count %>, 
                <%= @books.created_2days.count %>, 
                <%= @books.created_yesterday.count %>, 
                <%= @books.created_today.count %>
              ],
              borderColor: "rgba(0,0,255,1)",
              backgroundColor: "rgba(0,0,0,0)",
              tension: 0.4
            }
          ],
        },
        options: {
          title: {
            display: true,
            text: '7日間の投稿数の比較'
          },
          responsive: true,
          scales: {
            y:{
              suggestedMin: 0,
              suggestedMax: 10
            },
            x:{
              stacked: true
            },
          },
        }
      });
    });
  </script>

app/views/users/_search_form.html.erb
<br>
<div class='col-md-5'>
  <%= form_with url: user_search_form_path(user), method: :get, class: "row justify-content-center", local: false do |f| %>
    <div class="col-auto">
      <%= f.date_field :created_at, class: "form-control" %>
    </div>
    <div class="col-auto">
      <%= f.submit "検索" , class: "btn btn-primary"%>
    </div>
  <% end %>
</div>
<br>
<div class="search_form_table">
</div>

app/views/users/daily_posts_form.erb
$('.daily_posts_table').html(`
  <h2>検索結果</h2>
  <div class="card" >
    <div class="card-header">投稿数</div>
    <div class="card-body">
      <%= j( @books.count ) %>
    </div>
  </div>
`)

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/search_form.erb
$('.search_form_table').html(`
  <h2>検索結果</h2>
  <div class="card" >
    <div class="card-header">投稿数</div>
    <div class="card-body">
      <%= j( @books.count ) %>
    </div>
  </div>
`)

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %><br>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <%= render 'record' , user: @user %>
      <%= render 'search_form' , user: @user %>
    </div>
  </div>
</div>